; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = main

[env:lolin32_lite]
;platform = espressif32
platform = espressif32
board = lolin32_lite
framework = espidf
upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
monitor_filters = direct

; choose the latest espressif compiler toolchain
; as of october 2025, this is version 12.2.0+20230208
; platform_packages =
;     espressif/toolchain-xtensa-esp32@12.2.0+20230208

; disable default C++ 11/17
build_unflags =
    -std=gnu++11
    -std=gnu++17

; enable C++ 23
build_flags =
    -std=gnu++23
    -D CONFIG_HTTPD_WS_SUPPORT
;    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG

; build_type = debug

board_build.partitions = partitions.csv

board_build.embed_txtfiles = components/web_server/web_ui/index.html